"use client";
import { useState } from "react";

const INTEREST_RATES = [
  { label: "6.00% p.a. fixed for 1 year", rate: 6.0 },
  { label: "6.50% p.a. fixed for 5 years", rate: 6.5 },
  { label: "8.50% p.a. fixed for 10 years", rate: 8.5 },
];

const PROPERTY_TYPES = [
  "House and Lot",
  "Condominium",
  "Vacant Lot",
  "House Construction",
];

const LOAN_TERMS = [5, 10, 15, 20, 25, 30];

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

function generateImage(data: {
  propertyType: string;
  price: number;
  downPayment: number;
  dpPct: number;
  loanAmount: number;
  combinedIncome: number;
  selectedRate: { label: string; rate: number };
  results: Array<{ term: number; monthlyPayment: number }>;
  spotlightTerm: number;
  spotlightPayment: number;
  minRequiredIncome: number;
  spotlightRatio: number | null;
  spotlightWithin: boolean | null;
  maxLoanable: number | null;
}) {
  const W = 900;
  const rowH = 40;
  const numRows = data.results.length;

  // Calculate dynamic height
  const headerH = 90;
  const cardSectionH = 90; // cards
  const rateSectionH = 46;
  const tableH = 38 + numRows * rowH + 10;
  const spotlightH = 160;
  const footerNoticeH = 50;
  const footerBarH = 30;
  const padding = 20;

  const H =
    headerH +
    cardSectionH +
    rateSectionH +
    tableH +
    spotlightH +
    footerNoticeH +
    footerBarH +
    padding;

  const canvas = document.createElement("canvas");
  canvas.width = W * 2;
  canvas.height = H * 2;
  const ctx = canvas.getContext("2d")!;
  ctx.scale(2, 2);

  // Background
  ctx.fillStyle = "#f7f2f2";
  ctx.fillRect(0, 0, W, H);

  // Header bar
  ctx.fillStyle = "#8b1a1a";
  ctx.fillRect(0, 0, W, 90);
  ctx.fillStyle = "#6e1414";
  ctx.fillRect(0, 85, W, 5);

  // Header text
  ctx.fillStyle = "#fff";
  ctx.font = "bold 22px Arial";
  ctx.fillText("Home Loan Computation", 24, 38);
  ctx.fillStyle = "rgba(255,255,255,0.7)";
  ctx.font = "13px Arial";
  ctx.fillText("Generated by Alfima Realty Inc.", 24, 58);
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-PH", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  ctx.fillStyle = "rgba(255,255,255,0.6)";
  ctx.font = "11px Arial";
  ctx.textAlign = "right";
  ctx.fillText(dateStr, W - 24, 48);
  ctx.textAlign = "left";

  // ── Summary cards ──
  const cardY = 108,
    cardH = 72,
    cardGap = 12;
  const cards = [
    { label: "Property Type", value: data.propertyType },
    {
      label: "Property Price",
      value: `PHP ${data.price.toLocaleString("en-PH")}`,
    },
    {
      label: "Down Payment",
      value: `PHP ${data.downPayment.toLocaleString("en-PH")}`,
      sub: `${data.dpPct}% of price`,
    },
    {
      label: "Loan Amount",
      value: `PHP ${data.loanAmount.toLocaleString("en-PH")}`,
    },
    ...(data.combinedIncome > 0
      ? [
          {
            label: "Combined Income",
            value: `PHP ${data.combinedIncome.toLocaleString("en-PH")}`,
          },
        ]
      : []),
    ...(data.maxLoanable !== null
      ? [
          {
            label: "Est. Max Loanable",
            value: `PHP ${Math.round(data.maxLoanable).toLocaleString("en-PH")}`,
          },
        ]
      : []),
  ];
  const cardW = (W - 48 - cardGap * (cards.length - 1)) / cards.length;
  cards.forEach((card, i) => {
    const cx = 24 + i * (cardW + cardGap);
    ctx.fillStyle = "#fff";
    roundRect(ctx, cx, cardY, cardW, cardH, 8);
    ctx.fill();
    ctx.fillStyle = "#8b1a1a";
    roundRect(ctx, cx, cardY, 4, cardH, 4);
    ctx.fill();
    ctx.fillStyle = "#999";
    ctx.font = "10px Arial";
    ctx.fillText(card.label, cx + 14, cardY + 20);
    ctx.fillStyle = "#1a1a1a";
    ctx.font = `bold ${card.value.length > 18 ? 11 : 13}px Arial`;
    ctx.fillText(card.value, cx + 14, cardY + 42);
    if (card.sub) {
      ctx.fillStyle = "#8b1a1a";
      ctx.font = "10px Arial";
      ctx.fillText(card.sub, cx + 14, cardY + 58);
    }
  });

  // ── Interest Rate bar ──
  const rateY = cardY + cardH + 12;
  ctx.fillStyle = "#fff";
  roundRect(ctx, 24, rateY, W - 48, 32, 6);
  ctx.fill();
  ctx.fillStyle = "#8b1a1a";
  ctx.font = "bold 11px Arial";
  ctx.fillText("Interest Rate:", 38, rateY + 20);
  ctx.fillStyle = "#333";
  ctx.font = "11px Arial";
  ctx.fillText(data.selectedRate.label, 128, rateY + 20);

  // ── Loan breakdown table ──
  const tableY = rateY + 44;
  const cols = [
    { label: "Loan Term", x: 24, w: 120, align: "left" as const },
    { label: "Loan Amount", x: 144, w: 200, align: "right" as const },
    { label: "Monthly Amortization", x: 344, w: 210, align: "right" as const },
    { label: "Total Interest Paid", x: 554, w: 322, align: "right" as const },
  ];

  ctx.fillStyle = "#8b1a1a";
  roundRect(ctx, 24, tableY, W - 48, 36, 6);
  ctx.fill();
  cols.forEach((col) => {
    ctx.fillStyle = "#fff";
    ctx.font = "bold 11px Arial";
    ctx.textAlign = col.align;
    const tx = col.align === "right" ? col.x + col.w - 10 : col.x + 10;
    ctx.fillText(col.label, tx, tableY + 23);
  });
  ctx.textAlign = "left";

  data.results.forEach((row, idx) => {
    const ry = tableY + 36 + idx * rowH;
    ctx.fillStyle = idx % 2 === 0 ? "#fff" : "#fdf5f5";
    ctx.fillRect(24, ry, W - 48, rowH);
    const totalInterest =
      Math.round(row.monthlyPayment) * row.term * 12 - data.loanAmount;

    const cells = [
      { col: cols[0], val: `${row.term} years`, bold: true, color: "#8b1a1a" },
      {
        col: cols[1],
        val: `PHP ${data.loanAmount.toLocaleString("en-PH")}`,
        bold: false,
        color: "#333",
      },
      {
        col: cols[2],
        val: `PHP ${Math.round(row.monthlyPayment).toLocaleString("en-PH")}`,
        bold: true,
        color: "#1a1a2e",
      },
      {
        col: cols[3],
        val: `PHP ${totalInterest.toLocaleString("en-PH")}`,
        bold: false,
        color: "#a31515",
      },
    ];
    cells.forEach(({ col, val, bold, color }) => {
      ctx.fillStyle = color;
      ctx.font = bold ? "bold 12px Arial" : "12px Arial";
      ctx.textAlign = col.align;
      const tx = col.align === "right" ? col.x + col.w - 10 : col.x + 10;
      ctx.fillText(val, tx, ry + rowH / 2 + 5);
    });
    ctx.strokeStyle = "#f0e8e8";
    ctx.lineWidth = 0.5;
    ctx.beginPath();
    ctx.moveTo(24, ry + rowH);
    ctx.lineTo(W - 24, ry + rowH);
    ctx.stroke();
  });

  ctx.strokeStyle = "#ddd";
  ctx.lineWidth = 1;
  roundRect(ctx, 24, tableY, W - 48, 36 + data.results.length * rowH, 6);
  ctx.stroke();
  ctx.textAlign = "left";

  // ── Spotlight metrics section ──
  const spotY = tableY + 36 + data.results.length * rowH + 14;
  const spotH = 140;

  ctx.fillStyle = "#fff";
  roundRect(ctx, 24, spotY, W - 48, spotH, 8);
  ctx.fill();
  ctx.strokeStyle = "#e8d0d0";
  ctx.lineWidth = 1.5;
  roundRect(ctx, 24, spotY, W - 48, spotH, 8);
  ctx.stroke();

  // Section title
  ctx.fillStyle = "#8b1a1a";
  ctx.font = "bold 10px Arial";
  ctx.fillText(
    `MONTHLY AMORTIZATION & INCOME REQUIREMENT  ·  ${data.spotlightTerm}-YEAR TERM`,
    38,
    spotY + 18,
  );

  // Divider line
  ctx.strokeStyle = "#f0dada";
  ctx.lineWidth = 0.5;
  ctx.beginPath();
  ctx.moveTo(38, spotY + 24);
  ctx.lineTo(W - 38, spotY + 24);
  ctx.stroke();

  // Two metric boxes
  const mW = (W - 48 - 12) / 2;
  const mX1 = 24,
    mX2 = 24 + mW + 12;
  const mY = spotY + 32,
    mH = spotH - 40;

  // Box 1 — Estimated Monthly Amortization
  ctx.fillStyle = "#fdf5f5";
  roundRect(ctx, mX1, mY, mW, mH, 6);
  ctx.fill();
  ctx.strokeStyle = "#f0dada";
  ctx.lineWidth = 1;
  roundRect(ctx, mX1, mY, mW, mH, 6);
  ctx.stroke();

  ctx.fillStyle = "#999";
  ctx.font = "10px Arial";
  ctx.fillText("ESTIMATED MONTHLY AMORTIZATION", mX1 + 12, mY + 18);
  ctx.fillStyle = "#1a1a2e";
  ctx.font = "bold 18px Arial";
  ctx.fillText(
    `PHP ${Math.round(data.spotlightPayment).toLocaleString("en-PH")}`,
    mX1 + 12,
    mY + 44,
  );
  ctx.fillStyle = "#8b1a1a";
  ctx.font = "10px Arial";
  ctx.fillText(
    `${data.spotlightTerm}-yr term  ·  ${data.selectedRate.rate}% p.a.`,
    mX1 + 12,
    mY + 60,
  );

  if (data.spotlightRatio !== null) {
    const within = data.spotlightWithin;
    const pct = Math.round(data.spotlightRatio * 100);
    const badgeText = within
      ? `✓ Only ${pct}% of your income`
      : `✗ ${pct}% of income (over 30% limit)`;
    const badgeBg = within ? "#e6f4ea" : "#fdecea";
    const badgeFg = within ? "#1e7e34" : "#a31515";
    ctx.fillStyle = badgeBg;
    const bw = ctx.measureText(badgeText).width + 16;
    roundRect(ctx, mX1 + 12, mY + 72, bw, 20, 4);
    ctx.fill();
    ctx.fillStyle = badgeFg;
    ctx.font = "bold 10px Arial";
    ctx.fillText(badgeText, mX1 + 20, mY + 86);
  }

  // Box 2 — Minimum Required Income
  const hasIncome = data.minRequiredIncome > 0;
  ctx.fillStyle = hasIncome ? "#f0fdf4" : "#fdf5f5";
  roundRect(ctx, mX2, mY, mW, mH, 6);
  ctx.fill();
  ctx.strokeStyle = hasIncome ? "#c3e6cb" : "#f0dada";
  ctx.lineWidth = 1;
  roundRect(ctx, mX2, mY, mW, mH, 6);
  ctx.stroke();

  ctx.fillStyle = "#999";
  ctx.font = "10px Arial";
  ctx.fillText("MINIMUM REQUIRED INCOME", mX2 + 12, mY + 18);
  ctx.fillStyle = hasIncome ? "#1a5c2a" : "#1a1a2e";
  ctx.font = "bold 18px Arial";
  ctx.fillText(
    hasIncome
      ? `PHP ${Math.round(data.minRequiredIncome).toLocaleString("en-PH")}`
      : "—",
    mX2 + 12,
    mY + 44,
  );
  ctx.fillStyle = hasIncome ? "#2a7d3f" : "#999";
  ctx.font = "10px Arial";
  ctx.fillText("Monthly gross income needed (30% rule)", mX2 + 12, mY + 60);

  if (data.combinedIncome > 0 && hasIncome) {
    const surplus = data.combinedIncome >= data.minRequiredIncome;
    const diff = Math.abs(data.combinedIncome - data.minRequiredIncome);
    const badgeText = surplus
      ? `✓ Surplus PHP ${Math.round(diff).toLocaleString("en-PH")}/mo`
      : `✗ Shortfall PHP ${Math.round(diff).toLocaleString("en-PH")}/mo`;
    const badgeBg = surplus ? "#e6f4ea" : "#fdecea";
    const badgeFg = surplus ? "#1e7e34" : "#a31515";
    ctx.fillStyle = badgeBg;
    const bw = ctx.measureText(badgeText).width + 16;
    roundRect(ctx, mX2 + 12, mY + 72, bw, 20, 4);
    ctx.fill();
    ctx.fillStyle = badgeFg;
    ctx.font = "bold 10px Arial";
    ctx.fillText(badgeText, mX2 + 20, mY + 86);
  }

  // ── Footer notice ──
  const noticeY = spotY + spotH + 14;
  ctx.fillStyle = "#999";
  ctx.font = "10px Arial";
  ctx.fillText(
    "* All amounts in Philippine Peso (PHP). Computations are for illustration only and do not constitute an offer or approval.",
    24,
    noticeY,
  );
  ctx.fillText(
    "* Actual rates and terms will be confirmed by your account officer upon loan application.",
    24,
    noticeY + 16,
  );

  // ── Footer bar ──
  ctx.fillStyle = "#8b1a1a";
  ctx.fillRect(0, H - 28, W, 28);
  ctx.fillStyle = "rgba(255,255,255,0.8)";
  ctx.font = "10px Arial";
  ctx.textAlign = "center";
  ctx.fillText(
    "Alfima Realty Inc. •  For illustration purposes only",
    W / 2,
    H - 10,
  );
  ctx.textAlign = "left";

  const link = document.createElement("a");
  link.href = canvas.toDataURL("image/png");
  link.download = "alfima-home-loan-computation.png";
  link.click();
}

function fmt(v: number) {
  return Math.round(v).toLocaleString("en-PH");
}

function parseNum(val: string): number {
  return parseFloat(val.replace(/[^0-9.]/g, "")) || 0;
}

function fmtInput(val: string): string {
  const raw = val.replace(/[^0-9]/g, "");
  if (!raw) return "";
  return parseInt(raw).toLocaleString("en-PH");
}

function calcMonthly(loan: number, annualRate: number, years: number): number {
  const mr = annualRate / 100 / 12;
  const n = years * 12;
  if (mr === 0) return loan / n;
  return (loan * mr * Math.pow(1 + mr, n)) / (Math.pow(1 + mr, n) - 1);
}

function InfoIcon({ title }: { title: string }) {
  return (
    <span
      title={title}
      style={{
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        width: 14,
        height: 14,
        borderRadius: "50%",
        background: "#8b1a1a",
        color: "#fff",
        fontSize: 9,
        marginLeft: 4,
        cursor: "default",
        verticalAlign: "middle",
        flexShrink: 0,
      }}
    >
      i
    </span>
  );
}

export default function HomeLoanCalculator() {
  const [propertyType, setPropertyType] = useState("House and Lot");
  const [priceRaw, setPriceRaw] = useState("");
  const [incomeRaw, setIncomeRaw] = useState("");
  const [coIncomeRaw, setCoIncomeRaw] = useState("");
  const [showCoBorrower, setShowCoBorrower] = useState(false);
  const [dpPct, setDpPct] = useState(20);
  const [rateIndex, setRateIndex] = useState(0);
  const [customRate, setCustomRate] = useState("");
  const [useCustomRate, setUseCustomRate] = useState(false);
  const [computed, setComputed] = useState(false);
  const [spotlightTerm, setSpotlightTerm] = useState(20);
  const [show30Rule, setShow30Rule] = useState(false);

  const price = parseNum(priceRaw);
  const income = parseNum(incomeRaw);
  const coIncome = parseNum(coIncomeRaw);
  const combinedIncome = income + coIncome;

  const downPayment = price * (dpPct / 100);
  const loanAmount = price - downPayment;

  const selectedRate = useCustomRate
    ? {
        label: `${parseFloat(customRate) || 0}% p.a. (Custom)`,
        rate: parseFloat(customRate) || 0,
      }
    : INTEREST_RATES[rateIndex];

  const monthlyPayment20 =
    loanAmount > 0 ? calcMonthly(loanAmount, selectedRate.rate, 20) : 0;

  const maxLoanable =
    combinedIncome > 0
      ? (() => {
          const mr = selectedRate.rate / 100 / 12;
          const n = 20 * 12;
          if (mr === 0) return combinedIncome * 0.3 * n;
          return (
            (combinedIncome * 0.3 * (Math.pow(1 + mr, n) - 1)) /
            (mr * Math.pow(1 + mr, n))
          );
        })()
      : null;

  // Spotlight metrics
  const spotlightPayment =
    loanAmount > 0
      ? calcMonthly(loanAmount, selectedRate.rate, spotlightTerm)
      : 0;
  const minRequiredIncome = spotlightPayment > 0 ? spotlightPayment / 0.3 : 0;
  const spotlightRatio =
    combinedIncome > 0 ? spotlightPayment / combinedIncome : null;
  const spotlightWithin =
    spotlightRatio !== null ? spotlightRatio <= 0.3 : null;

  function handlePriceInput(val: string) {
    setPriceRaw(fmtInput(val));
  }
  function handleIncomeInput(val: string) {
    setIncomeRaw(fmtInput(val));
  }
  function handleCoIncomeInput(val: string) {
    setCoIncomeRaw(fmtInput(val));
  }

  function handleTypeChange(val: string) {
    setPropertyType(val);
    if (val === "House Construction") {
      setPriceRaw("");
      setIncomeRaw("");
      setCoIncomeRaw("");
      setDpPct(20);
      setRateIndex(0);
      setUseCustomRate(false);
      setCustomRate("");
      setComputed(false);
      setShowCoBorrower(false);
    }
  }

  function handleReset() {
    setPropertyType("House and Lot");
    setPriceRaw("");
    setIncomeRaw("");
    setCoIncomeRaw("");
    setShowCoBorrower(false);
    setDpPct(20);
    setRateIndex(0);
    setCustomRate("");
    setUseCustomRate(false);
    setComputed(false);
    setSpotlightTerm(20);
    setShow30Rule(false);
  }

  const sliderPct = ((dpPct - 5) / 85) * 87 + 5;

  return (
    <>
      <style>{`
        .hlc-root {
          display: grid;
          grid-template-columns: 380px 1fr;
          min-height: 600px;
          font-family: 'Segoe UI', system-ui, sans-serif;
          background: #f5f5f5;
        }
        @media (max-width: 900px) {
          .hlc-root { grid-template-columns: 1fr; }
          .hlc-right { border-left: none !important; border-top: 1px solid #dde4ea; }
        }
        .hlc-left {
          background: #fff;
          border: 1px solid #dde4ea;
          border-right: none;
          display: flex;
          flex-direction: column;
          min-width: 0;
        }
        .hlc-right {
          background: #fff;
          border: 1px solid #dde4ea;
          display: flex;
          flex-direction: column;
          min-width: 0;
        }
        .hlc-panel-header {
          background: #8b1a1a;
          padding: 14px 20px;
          flex-shrink: 0;
        }
        .hlc-panel-body {
          padding: 18px 20px;
          overflow-y: auto;
          flex: 1;
        }
        .hlc-label {
          display: flex;
          align-items: center;
          font-size: 12px;
          color: #333;
          margin-bottom: 5px;
          font-weight: 600;
        }
        .hlc-input {
          width: 100%;
          border: 1.5px solid #c8d6e0;
          border-radius: 6px;
          padding: 9px 12px;
          font-size: 13px;
          color: #1a1a2e;
          background: #fff;
          outline: none;
          box-sizing: border-box;
          transition: border-color 0.15s;
          -webkit-appearance: none;
        }
        .hlc-input:focus { border-color: #8b1a1a; }
        .hlc-input-ro {
          width: 100%;
          border: 1.5px solid #e0e0e0;
          border-radius: 6px;
          padding: 9px 12px;
          font-size: 13px;
          color: #555;
          background: #f8f8f8;
          outline: none;
          box-sizing: border-box;
        }
        .hlc-select-wrap { position: relative; margin-bottom: 4px; }
        .hlc-select {
          width: 100%;
          border: 1.5px solid #c8d6e0;
          border-radius: 6px;
          padding: 9px 30px 9px 12px;
          font-size: 13px;
          color: #1a1a2e;
          background: #fff;
          outline: none;
          appearance: none;
          -webkit-appearance: none;
          box-sizing: border-box;
          transition: border-color 0.15s;
          cursor: pointer;
        }
        .hlc-select:focus { border-color: #8b1a1a; }
        .hlc-select-arrow {
          position: absolute; right: 10px; top: 50%;
          transform: translateY(-50%);
          color: #8b1a1a; pointer-events: none; font-size: 11px;
        }
        .hlc-hint {
          font-size: 11px; color: #999;
          margin: 0 0 12px; line-height: 1.4;
        }
        .hlc-field { margin-bottom: 14px; }

        .hlc-coborrower-toggle {
          display: flex; align-items: center; gap: 6px;
          background: none; border: 1.5px dashed #d0b0b0;
          border-radius: 6px; padding: 8px 12px;
          font-size: 12px; color: #8b1a1a; font-weight: 600;
          cursor: pointer; width: 100%; margin-bottom: 14px;
          transition: background 0.15s;
        }
        .hlc-coborrower-toggle:hover { background: #fdf5f5; }

        .hlc-coborrower-box {
          background: #fdf5f5;
          border: 1px solid #f0dada;
          border-radius: 8px;
          padding: 12px 14px;
          margin-bottom: 14px;
        }
        .hlc-coborrower-header {
          display: flex; align-items: center; justify-content: space-between;
          margin-bottom: 10px;
        }
        .hlc-coborrower-title {
          font-size: 11px; font-weight: 700;
          color: #8b1a1a; text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .hlc-coborrower-remove {
          background: none; border: none; cursor: pointer;
          color: #aaa; font-size: 16px; padding: 0; line-height: 1;
          transition: color 0.15s;
        }
        .hlc-coborrower-remove:hover { color: #8b1a1a; }

        .hlc-combined-badge {
          background: #8b1a1a;
          color: #fff;
          border-radius: 6px;
          padding: 8px 12px;
          margin-bottom: 14px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-wrap: wrap;
          gap: 4px;
        }

        .hlc-btn-primary {
          background: linear-gradient(135deg, #a31515, #6e1414);
          color: #fff; border: none; border-radius: 6px;
          padding: 11px 24px; font-size: 13px; font-weight: 700;
          cursor: pointer; touch-action: manipulation;
          -webkit-tap-highlight-color: transparent;
          min-height: 44px;
          transition: opacity 0.15s, transform 0.1s;
          letter-spacing: 0.3px;
        }
        .hlc-btn-primary:hover { opacity: 0.92; }
        .hlc-btn-primary:active { transform: scale(0.98); }
        .hlc-btn-outline {
          background: #fff; color: #8b1a1a;
          border: 2px solid #8b1a1a; border-radius: 6px;
          padding: 11px 24px; font-size: 13px; font-weight: 700;
          cursor: pointer; touch-action: manipulation;
          -webkit-tap-highlight-color: transparent;
          min-height: 44px; transition: background 0.15s, color 0.15s;
        }
        .hlc-btn-outline:hover { background: #fdf5f5; }
        .hlc-summary-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
          gap: 10px; padding-bottom: 14px;
          border-bottom: 1px solid #eee; margin-bottom: 14px;
        }
        .hlc-summary-card {
          background: #fdf5f5;
          border: 1px solid #f0dada;
          border-radius: 8px; padding: 10px 12px;
        }
        .hlc-table-wrap {
          overflow-x: auto; margin-bottom: 14px;
          border-radius: 8px; border: 1px solid #e8eef4;
        }
        .hlc-table {
          width: 100%; border-collapse: collapse;
          font-size: 12px; min-width: 420px;
        }
        .hlc-th {
          padding: 11px 12px; color: #fff;
          text-align: center; font-weight: 700;
          font-size: 11px; white-space: nowrap;
          background: #8b1a1a;
        }
        .hlc-th:first-child { border-radius: 7px 0 0 0; }
        .hlc-th:last-child  { border-radius: 0 7px 0 0; }
        .hlc-td {
          padding: 10px 12px; text-align: center;
          border-bottom: 1px solid #f0eded; font-size: 12px;
        }
        .hlc-tr-even { background: #fff; }
        .hlc-tr-odd  { background: #fdf8f8; }
        .hlc-right-body {
          padding: 16px 20px; flex: 1; overflow-y: auto;
        }
        .hlc-notice {
          padding: 0 20px 16px; flex-shrink: 0;
          border-top: 1px solid #f0f0f0;
        }
        .hlc-slider-wrap { position: relative; margin: 12px 0 6px; }
        .hlc-slider-tooltip {
          position: absolute; top: -24px;
          background: #8b1a1a; color: #fff;
          font-size: 10px; padding: 2px 6px;
          border-radius: 4px; white-space: nowrap;
          pointer-events: none; transform: translateX(-50%);
        }
        .hlc-slider-ticks {
          display: flex; justify-content: space-between;
          font-size: 9px; color: #bbb; margin-bottom: 12px;
        }
        input[type=range] { width: 100%; accent-color: #8b1a1a; touch-action: manipulation; }
        .hlc-empty {
          display: flex; flex-direction: column;
          align-items: center; justify-content: center;
          padding: 60px 24px; flex: 1;
        }

        /* ── Spotlight metrics section ── */
        .hlc-spotlight {
          background: #fff;
          border: 1.5px solid #e8d0d0;
          border-radius: 10px;
          padding: 14px 16px;
          margin-bottom: 14px;
        }
        .hlc-spotlight-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 12px;
          flex-wrap: wrap;
          gap: 8px;
        }
        .hlc-spotlight-title {
          font-size: 11px;
          font-weight: 700;
          color: #8b1a1a;
          text-transform: uppercase;
          letter-spacing: 0.6px;
        }
        .hlc-spotlight-term-select {
          border: 1.5px solid #c8d6e0;
          border-radius: 6px;
          padding: 5px 24px 5px 10px;
          font-size: 12px;
          color: #1a1a2e;
          background: #fff;
          outline: none;
          appearance: none;
          -webkit-appearance: none;
          cursor: pointer;
        }
        .hlc-spotlight-term-select:focus { border-color: #8b1a1a; }
        .hlc-metrics-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 10px;
        }
        .hlc-metric-card {
          background: #fdf5f5;
          border: 1px solid #f0dada;
          border-radius: 8px;
          padding: 10px 14px;
        }
        .hlc-metric-label {
          font-size: 10px;
          color: #999;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 4px;
        }
        .hlc-metric-value {
          font-size: 16px;
          font-weight: 700;
          color: #1a1a2e;
        }
        .hlc-metric-sub {
          font-size: 10px;
          color: #8b1a1a;
          margin-top: 2px;
        }
        .hlc-metric-income {
          background: #f0fdf4;
          border-color: #c3e6cb;
        }
        .hlc-metric-income .hlc-metric-value { color: #1a5c2a; }
        .hlc-metric-income .hlc-metric-sub { color: #2a7d3f; }

        /* ── 30% Rule explainer ── */
        .hlc-rule-toggle {
          display: flex;
          align-items: center;
          justify-content: space-between;
          background: none;
          border: 1.5px solid #e0c8c8;
          border-radius: 8px;
          padding: 10px 14px;
          width: 100%;
          cursor: pointer;
          margin-bottom: 8px;
          transition: background 0.15s;
        }
        .hlc-rule-toggle:hover { background: #fdf5f5; }
        .hlc-rule-toggle-left {
          display: flex;
          align-items: center;
          gap: 8px;
        }
        .hlc-rule-icon {
          width: 22px;
          height: 22px;
          border-radius: 50%;
          background: #8b1a1a;
          color: #fff;
          font-size: 12px;
          font-weight: 700;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
        }
        .hlc-rule-toggle-label {
          font-size: 12px;
          font-weight: 700;
          color: #8b1a1a;
        }
        .hlc-rule-caret {
          font-size: 11px;
          color: #8b1a1a;
          transition: transform 0.2s;
        }
        .hlc-rule-caret.open { transform: rotate(180deg); }
        .hlc-rule-body {
          background: #fffaf9;
          border: 1px solid #f0dada;
          border-radius: 8px;
          padding: 14px 16px;
          margin-bottom: 14px;
        }
        .hlc-rule-section {
          margin-bottom: 12px;
        }
        .hlc-rule-section:last-child { margin-bottom: 0; }
        .hlc-rule-section-title {
          font-size: 11px;
          font-weight: 700;
          color: #8b1a1a;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin-bottom: 4px;
        }
        .hlc-rule-section-body {
          font-size: 12px;
          color: #444;
          line-height: 1.6;
        }
        .hlc-rule-example {
          background: #fdf5f5;
          border-left: 3px solid #8b1a1a;
          border-radius: 0 6px 6px 0;
          padding: 8px 12px;
          margin-top: 6px;
          font-size: 11px;
          color: #555;
          line-height: 1.6;
        }
        .hlc-rule-badges {
          display: flex;
          gap: 8px;
          margin-top: 8px;
          flex-wrap: wrap;
        }
        .hlc-rule-badge {
          padding: 4px 10px;
          border-radius: 4px;
          font-size: 11px;
          font-weight: 600;
        }
        .hlc-badge-green {
          background: #e6f4ea;
          color: #1e7e34;
        }
        .hlc-badge-red {
          background: #fdecea;
          color: #a31515;
        }

        @media (max-width: 480px) {
          .hlc-panel-body { padding: 14px 14px; }
          .hlc-right-body { padding: 14px 14px; }
          .hlc-notice { padding: 0 14px 14px; }
          .hlc-btn-primary, .hlc-btn-outline { padding: 11px 14px; font-size: 12px; }
          .hlc-table { font-size: 11px; min-width: 340px; }
          .hlc-th, .hlc-td { padding: 8px 8px; font-size: 10px; }
          .hlc-metrics-grid { grid-template-columns: 1fr; }
        }
      `}</style>

      <div className="hlc-root mt-16">
        {/* ── LEFT PANEL ── */}
        <div className="hlc-left">
          <div className="hlc-panel-header">
            <p
              style={{
                color: "#fff",
                fontSize: 14,
                fontWeight: 700,
                margin: 0,
              }}
            >
              Fill in with preferred details.
            </p>
          </div>

          <div className="hlc-panel-body">
            <p
              style={{
                fontSize: 11,
                color: "#888",
                marginBottom: 14,
                marginTop: 0,
              }}
            >
              (*) is a required field
            </p>

            {/* Property Type */}
            <div className="hlc-field">
              <label className="hlc-label">
                Property Type <InfoIcon title="Select the type of property" />
              </label>
              <div className="hlc-select-wrap">
                <select
                  className="hlc-select"
                  value={propertyType}
                  onChange={(e) => handleTypeChange(e.target.value)}
                >
                  {PROPERTY_TYPES.map((t) => (
                    <option key={t}>{t}</option>
                  ))}
                </select>
                <span className="hlc-select-arrow">▾</span>
              </div>
              <p className="hlc-hint">
                Selecting House Construction will reset the fields below.
              </p>
            </div>

            {/* Primary Borrower Income */}
            <div className="hlc-field">
              <label className="hlc-label">
                Monthly Gross Income (Primary Borrower) *{" "}
                <InfoIcon title="Used to check 30% income rule" />
              </label>
              <input
                className="hlc-input"
                style={{ marginBottom: 4 }}
                value={incomeRaw}
                onChange={(e) => handleIncomeInput(e.target.value)}
                placeholder="PHP 0"
                inputMode="numeric"
              />
              <p className="hlc-hint">
                Used to estimate maximum loanable amount (30% rule).
              </p>
            </div>

            {/* Co-Borrower toggle */}
            {!showCoBorrower ? (
              <button
                className="hlc-coborrower-toggle"
                onClick={() => setShowCoBorrower(true)}
              >
                <span style={{ fontSize: 16, lineHeight: 1 }}>+</span>
                Add Co-Borrower Income
              </button>
            ) : (
              <div className="hlc-coborrower-box">
                <div className="hlc-coborrower-header">
                  <span className="hlc-coborrower-title">
                    Co-Borrower Income
                  </span>
                  <button
                    className="hlc-coborrower-remove"
                    onClick={() => {
                      setShowCoBorrower(false);
                      setCoIncomeRaw("");
                    }}
                    title="Remove co-borrower"
                  >
                    ×
                  </button>
                </div>
                <label className="hlc-label">
                  Monthly Gross Income (Co-Borrower){" "}
                  <InfoIcon title="Combined with primary borrower for 30% rule" />
                </label>
                <input
                  className="hlc-input"
                  style={{ marginBottom: 4, background: "#fff" }}
                  value={coIncomeRaw}
                  onChange={(e) => handleCoIncomeInput(e.target.value)}
                  placeholder="PHP 0"
                  inputMode="numeric"
                />
                <p className="hlc-hint" style={{ marginBottom: 0 }}>
                  Combined with primary borrower income for loan qualification.
                </p>
              </div>
            )}

            {/* Combined Income Badge */}
            {income > 0 && coIncome > 0 && (
              <div className="hlc-combined-badge">
                <span style={{ fontSize: 11, fontWeight: 700, opacity: 0.85 }}>
                  Combined Monthly Income
                </span>
                <span style={{ fontSize: 14, fontWeight: 700 }}>
                  PHP {fmt(combinedIncome)}
                </span>
              </div>
            )}

            {/* Property Price */}
            <div className="hlc-field">
              <label className="hlc-label">
                Property Price * <InfoIcon title="Total property price" />
              </label>
              <input
                className="hlc-input"
                style={{ marginBottom: 4 }}
                value={priceRaw}
                onChange={(e) => handlePriceInput(e.target.value)}
                placeholder="PHP 0"
                inputMode="numeric"
              />
            </div>

            {/* Downpayment */}
            <div className="hlc-field">
              <label className="hlc-label">
                Downpayment{" "}
                <InfoIcon title="Down payment percentage (min 5%)" />
              </label>
              <input
                className="hlc-input-ro"
                readOnly
                value={price > 0 ? `PHP ${fmt(downPayment)}` : ""}
                style={{ marginBottom: 0 }}
              />
              <div className="hlc-slider-wrap">
                <div
                  className="hlc-slider-tooltip"
                  style={{ left: `${sliderPct}%` }}
                >
                  {dpPct}%
                </div>
                <input
                  type="range"
                  min={5}
                  max={90}
                  step={5}
                  value={dpPct}
                  onChange={(e) => setDpPct(Number(e.target.value))}
                />
              </div>
              <div className="hlc-slider-ticks">
                {[5, 10, 20, 30, 40, 50, 60, 70, 80, 90].map((v) => (
                  <span key={v}>{v}%</span>
                ))}
              </div>
            </div>

            {/* Loan Amount */}
            <div className="hlc-field">
              <label className="hlc-label">
                Loan Amount{" "}
                <InfoIcon title="Computed from price minus down payment" />
              </label>
              <input
                className="hlc-input-ro"
                readOnly
                value={price > 0 ? `PHP ${fmt(loanAmount)}` : ""}
                style={{ marginBottom: 4 }}
              />
            </div>

            {/* Monthly Payment Preview */}
            <div className="hlc-field">
              <label className="hlc-label">
                Monthly Payment (20 yrs est.){" "}
                <InfoIcon title="Estimated monthly amortization over 20 years" />
              </label>
              <input
                className="hlc-input-ro"
                readOnly
                value={price > 0 ? `PHP ${fmt(monthlyPayment20)}` : ""}
                style={{ marginBottom: 4 }}
              />
            </div>

            {/* Interest Rate */}
            <div className="hlc-field">
              <label className="hlc-label">
                Interest Rate *{" "}
                <InfoIcon title="Select applicable interest rate" />
              </label>
              <div className="hlc-select-wrap">
                <select
                  className="hlc-select"
                  value={useCustomRate ? -1 : rateIndex}
                  onChange={(e) => {
                    if (e.target.value === "-1") setUseCustomRate(true);
                    else {
                      setUseCustomRate(false);
                      setRateIndex(Number(e.target.value));
                    }
                  }}
                >
                  {INTEREST_RATES.map((r, i) => (
                    <option key={i} value={i}>
                      {r.label}
                    </option>
                  ))}
                  <option value="-1">Custom Rate</option>
                </select>
                <span className="hlc-select-arrow">▾</span>
              </div>
              {useCustomRate && (
                <div style={{ marginTop: 8 }}>
                  <label className="hlc-label">
                    Enter Custom Rate (%){" "}
                    <InfoIcon title="For illustration only" />
                  </label>
                  <input
                    className="hlc-input"
                    type="number"
                    min="0"
                    max="100"
                    step="0.01"
                    placeholder="e.g. 6.5"
                    value={customRate}
                    onChange={(e) => setCustomRate(e.target.value)}
                    inputMode="decimal"
                    style={{ marginBottom: 4 }}
                  />
                </div>
              )}
              <p className="hlc-hint" style={{ marginTop: 6 }}>
                Rates subject to change without notice. Custom rate is for
                illustration only.
              </p>
            </div>

            {/* Buttons */}
            <div style={{ display: "flex", gap: 10, marginTop: 6 }}>
              <button
                className="hlc-btn-primary"
                style={{ flex: 1 }}
                onClick={() => setComputed(true)}
              >
                Compute
              </button>
              <button
                className="hlc-btn-outline"
                style={{ flex: 1 }}
                onClick={handleReset}
              >
                Reset
              </button>
            </div>
          </div>
        </div>

        {/* ── RIGHT PANEL ── */}
        <div className="hlc-right">
          <div className="hlc-panel-header">
            <p
              style={{
                color: "#fff",
                fontSize: 14,
                fontWeight: 700,
                margin: 0,
              }}
            >
              Results
            </p>
          </div>

          {!computed ? (
            <div className="hlc-empty">
              <svg width="72" height="72" viewBox="0 0 80 80" fill="none">
                <circle
                  cx="40"
                  cy="40"
                  r="38"
                  fill="#f5eded"
                  stroke="#e0c8c8"
                  strokeWidth="1.5"
                />
                <rect
                  x="18"
                  y="22"
                  width="44"
                  height="32"
                  rx="3"
                  fill="#fff"
                  stroke="#8b1a1a"
                  strokeWidth="1.5"
                />
                <rect
                  x="22"
                  y="27"
                  width="20"
                  height="3"
                  rx="1"
                  fill="#8b1a1a"
                />
                <rect
                  x="22"
                  y="33"
                  width="36"
                  height="2"
                  rx="1"
                  fill="#e0c8c8"
                />
                <rect
                  x="22"
                  y="38"
                  width="30"
                  height="2"
                  rx="1"
                  fill="#e0c8c8"
                />
                <rect
                  x="22"
                  y="43"
                  width="24"
                  height="2"
                  rx="1"
                  fill="#e0c8c8"
                />
              </svg>
              <p
                style={{
                  fontSize: 12,
                  color: "#999",
                  marginTop: 14,
                  textAlign: "center",
                  lineHeight: 1.6,
                }}
              >
                Fill in the details on the left and click{" "}
                <strong style={{ color: "#8b1a1a" }}>Compute</strong> to see
                your home loan breakdown.
              </p>
            </div>
          ) : (
            <>
              <div className="hlc-right-body">
                {/* Summary cards */}
                <div className="hlc-summary-grid">
                  <div className="hlc-summary-card">
                    <p
                      style={{
                        fontSize: 10,
                        color: "#999",
                        margin: "0 0 4px",
                        textTransform: "uppercase",
                        letterSpacing: "0.5px",
                      }}
                    >
                      Property Price
                    </p>
                    <p
                      style={{
                        fontSize: 15,
                        fontWeight: 700,
                        color: "#1a1a2e",
                        margin: 0,
                      }}
                    >
                      PHP {fmt(price)}
                    </p>
                  </div>
                  <div className="hlc-summary-card">
                    <p
                      style={{
                        fontSize: 10,
                        color: "#999",
                        margin: "0 0 4px",
                        textTransform: "uppercase",
                        letterSpacing: "0.5px",
                      }}
                    >
                      Loan Amount
                    </p>
                    <p
                      style={{
                        fontSize: 15,
                        fontWeight: 700,
                        color: "#1a1a2e",
                        margin: 0,
                      }}
                    >
                      PHP {fmt(loanAmount)}
                    </p>
                  </div>
                  <div className="hlc-summary-card">
                    <p
                      style={{
                        fontSize: 10,
                        color: "#999",
                        margin: "0 0 4px",
                        textTransform: "uppercase",
                        letterSpacing: "0.5px",
                      }}
                    >
                      Down Payment
                    </p>
                    <p
                      style={{
                        fontSize: 15,
                        fontWeight: 700,
                        color: "#1a1a2e",
                        margin: 0,
                      }}
                    >
                      PHP {fmt(downPayment)}
                    </p>
                    <p style={{ fontSize: 10, color: "#8b1a1a", margin: 0 }}>
                      {dpPct}% of price
                    </p>
                  </div>
                  {combinedIncome > 0 && (
                    <div
                      className="hlc-summary-card"
                      style={{ borderColor: "#8b1a1a", background: "#fff8f8" }}
                    >
                      <p
                        style={{
                          fontSize: 10,
                          color: "#8b1a1a",
                          margin: "0 0 4px",
                          textTransform: "uppercase",
                          letterSpacing: "0.5px",
                          fontWeight: 700,
                        }}
                      >
                        {coIncome > 0 ? "Combined Income" : "Monthly Income"}
                      </p>
                      <p
                        style={{
                          fontSize: 15,
                          fontWeight: 700,
                          color: "#1a1a2e",
                          margin: 0,
                        }}
                      >
                        PHP {fmt(combinedIncome)}
                      </p>
                      {coIncome > 0 && (
                        <p style={{ fontSize: 10, color: "#888", margin: 0 }}>
                          {fmt(income)} + {fmt(coIncome)}
                        </p>
                      )}
                    </div>
                  )}
                  {maxLoanable !== null && (
                    <div className="hlc-summary-card">
                      <p
                        style={{
                          fontSize: 10,
                          color: "#999",
                          margin: "0 0 4px",
                          textTransform: "uppercase",
                          letterSpacing: "0.5px",
                        }}
                      >
                        Est. Max Loanable
                      </p>
                      <p
                        style={{
                          fontSize: 15,
                          fontWeight: 700,
                          color: "#1a1a2e",
                          margin: 0,
                        }}
                      >
                        PHP {fmt(maxLoanable)}
                      </p>
                    </div>
                  )}
                </div>

                {/* Rate label */}
                <div
                  style={{
                    background: "#fdf5f5",
                    border: "1px solid #f0dada",
                    borderRadius: 6,
                    padding: "8px 12px",
                    marginBottom: 14,
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    flexWrap: "wrap",
                  }}
                >
                  <span
                    style={{ fontSize: 11, color: "#8b1a1a", fontWeight: 700 }}
                  >
                    Interest Rate:
                  </span>
                  <span style={{ fontSize: 11, color: "#333" }}>
                    {selectedRate.label}
                  </span>
                </div>

                <p
                  style={{
                    fontSize: 11,
                    color: "#aaa",
                    marginBottom: 12,
                    fontStyle: "italic",
                    lineHeight: 1.5,
                  }}
                >
                  Rates subject to change without notice. Custom-input rate is
                  for illustration only.
                </p>

                {/* Table */}
                <div className="hlc-table-wrap">
                  <table className="hlc-table">
                    <thead>
                      <tr>
                        <th className="hlc-th">Loan Term</th>
                        <th className="hlc-th">Loan Amount</th>
                        <th className="hlc-th">Monthly Amort.</th>
                        <th className="hlc-th">Total Interest</th>
                      </tr>
                    </thead>
                    <tbody>
                      {LOAN_TERMS.map((yr, idx) => {
                        const mp = calcMonthly(
                          loanAmount,
                          selectedRate.rate,
                          yr,
                        );
                        const totalInterest =
                          Math.round(mp) * yr * 12 - loanAmount;
                        return (
                          <tr
                            key={yr}
                            className={
                              idx % 2 === 0 ? "hlc-tr-even" : "hlc-tr-odd"
                            }
                          >
                            <td
                              className="hlc-td"
                              style={{ fontWeight: 700, color: "#8b1a1a" }}
                            >
                              {yr} yrs
                            </td>
                            <td className="hlc-td" style={{ color: "#333" }}>
                              <span style={{ color: "#aaa", fontSize: 10 }}>
                                PHP{" "}
                              </span>
                              {fmt(loanAmount)}
                            </td>
                            <td
                              className="hlc-td"
                              style={{ color: "#1a1a2e", fontWeight: 600 }}
                            >
                              <span style={{ color: "#aaa", fontSize: 10 }}>
                                PHP{" "}
                              </span>
                              {fmt(mp)}
                            </td>
                            <td
                              className="hlc-td"
                              style={{ color: "#a31515", fontSize: 11 }}
                            >
                              PHP {fmt(totalInterest)}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>

                {/* ── SPOTLIGHT METRICS ── */}
                <div className="hlc-spotlight">
                  <div className="hlc-spotlight-header">
                    <span className="hlc-spotlight-title">
                      Monthly Amortization & Income Requirement
                    </span>
                    <div
                      style={{ position: "relative", display: "inline-block" }}
                    >
                      <select
                        className="hlc-spotlight-term-select"
                        value={spotlightTerm}
                        onChange={(e) =>
                          setSpotlightTerm(Number(e.target.value))
                        }
                      >
                        {LOAN_TERMS.map((yr) => (
                          <option key={yr} value={yr}>
                            {yr}-year term
                          </option>
                        ))}
                      </select>
                      <span
                        style={{
                          position: "absolute",
                          right: 8,
                          top: "50%",
                          transform: "translateY(-50%)",
                          color: "#8b1a1a",
                          pointerEvents: "none",
                          fontSize: 10,
                        }}
                      >
                        ▾
                      </span>
                    </div>
                  </div>

                  <div className="hlc-metrics-grid">
                    {/* Estimated Monthly Amortization */}
                    <div className="hlc-metric-card">
                      <div className="hlc-metric-label">
                        Estimated Monthly Amortization
                      </div>
                      <div className="hlc-metric-value">
                        {loanAmount > 0 ? `PHP ${fmt(spotlightPayment)}` : "—"}
                      </div>
                      <div className="hlc-metric-sub">
                        {loanAmount > 0
                          ? `${spotlightTerm}-yr term · ${selectedRate.rate}% p.a.`
                          : "Enter property price"}
                      </div>
                      {/* Status indicator vs combined income */}
                      {spotlightRatio !== null && (
                        <div style={{ marginTop: 6 }}>
                          <span
                            style={{
                              background: spotlightWithin
                                ? "#e6f4ea"
                                : "#fdecea",
                              color: spotlightWithin ? "#1e7e34" : "#a31515",
                              fontSize: 10,
                              padding: "2px 8px",
                              borderRadius: 4,
                              fontWeight: 700,
                            }}
                          >
                            {spotlightWithin
                              ? `✓ Only ${Math.round(spotlightRatio * 100)}% of your income`
                              : `✗ ${Math.round(spotlightRatio * 100)}% of your income (over 30% limit)`}
                          </span>
                        </div>
                      )}
                    </div>

                    {/* Minimum Required Income */}
                    <div
                      className={`hlc-metric-card${loanAmount > 0 ? " hlc-metric-income" : ""}`}
                    >
                      <div className="hlc-metric-label">
                        Minimum Required Income
                      </div>
                      <div className="hlc-metric-value">
                        {loanAmount > 0 ? `PHP ${fmt(minRequiredIncome)}` : "—"}
                      </div>
                      <div className="hlc-metric-sub">
                        {loanAmount > 0
                          ? `Monthly gross income needed (30% rule)`
                          : "Enter property price"}
                      </div>
                      {/* Shortfall or surplus vs combined income */}
                      {combinedIncome > 0 && loanAmount > 0 && (
                        <div style={{ marginTop: 6 }}>
                          {combinedIncome >= minRequiredIncome ? (
                            <span
                              style={{
                                background: "#e6f4ea",
                                color: "#1e7e34",
                                fontSize: 10,
                                padding: "2px 8px",
                                borderRadius: 4,
                                fontWeight: 700,
                              }}
                            >
                              ✓ Surplus PHP{" "}
                              {fmt(combinedIncome - minRequiredIncome)}/mo
                            </span>
                          ) : (
                            <span
                              style={{
                                background: "#fdecea",
                                color: "#a31515",
                                fontSize: 10,
                                padding: "2px 8px",
                                borderRadius: 4,
                                fontWeight: 700,
                              }}
                            >
                              ✗ Shortfall PHP{" "}
                              {fmt(minRequiredIncome - combinedIncome)}/mo
                            </span>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* ── 30% RULE EXPLAINER ── */}
                <button
                  className="hlc-rule-toggle"
                  onClick={() => setShow30Rule((v) => !v)}
                >
                  <div className="hlc-rule-toggle-left">
                    <div className="hlc-rule-icon">?</div>
                    <span className="hlc-rule-toggle-label">
                      What is the 30% Rule?
                    </span>
                  </div>
                  <span
                    className={`hlc-rule-caret${show30Rule ? " open" : ""}`}
                  >
                    ▾
                  </span>
                </button>

                {show30Rule && (
                  <div className="hlc-rule-body">
                    <div className="hlc-rule-section">
                      <div className="hlc-rule-section-title">Definition</div>
                      <div className="hlc-rule-section-body">
                        The <strong>30% Rule</strong> (also called the
                        debt-to-income guideline) states that your monthly
                        housing loan payment should not exceed{" "}
                        <strong>30% of your gross monthly income</strong>. Most
                        Philippine banks and lenders use this benchmark to
                        assess a borrower's repayment capacity.
                      </div>
                    </div>

                    <div className="hlc-rule-section">
                      <div className="hlc-rule-section-title">Formula</div>
                      <div className="hlc-rule-section-body">
                        <div className="hlc-rule-example">
                          Maximum Monthly Amortization = Gross Monthly Income ×
                          30%
                          <br />
                          <br />
                          <strong>Example:</strong> If your gross monthly income
                          is PHP 50,000:
                          <br />
                          Max amortization = PHP 50,000 × 0.30 ={" "}
                          <strong>PHP 15,000/month</strong>
                        </div>
                      </div>
                    </div>

                    <div className="hlc-rule-section">
                      <div className="hlc-rule-section-title">
                        How it affects your loan
                      </div>
                      <div className="hlc-rule-section-body">
                        Banks check this ratio to protect both the borrower and
                        the institution. Staying within 30% ensures you have
                        enough budget left for daily expenses, emergencies, and
                        other financial obligations.
                      </div>
                      <div className="hlc-rule-badges">
                        <span className="hlc-rule-badge hlc-badge-green">
                          ✓ ≤30% — Loan likely approved
                        </span>
                        <span className="hlc-rule-badge hlc-badge-red">
                          ✗ &gt;30% — May need co-borrower or lower loan
                        </span>
                      </div>
                    </div>

                    <div className="hlc-rule-section">
                      <div className="hlc-rule-section-title">
                        Tips to qualify
                      </div>
                      <div className="hlc-rule-section-body">
                        • Add a <strong>co-borrower</strong> (spouse, sibling,
                        parent) to increase combined income
                        <br />• Increase your <strong>down payment</strong> to
                        reduce the loan amount
                        <br />• Choose a <strong>longer loan term</strong> to
                        lower monthly payments
                        <br />• Wait until income grows before applying for a
                        larger loan
                      </div>
                    </div>

                    <div
                      style={{
                        fontSize: 11,
                        color: "#999",
                        fontStyle: "italic",
                        marginTop: 8,
                      }}
                    >
                      * This calculator uses the 30% rule for illustration.
                      Actual bank policies may vary.
                    </div>
                  </div>
                )}

                <button
                  className="hlc-btn-primary"
                  style={{ width: "100%", marginBottom: 4 }}
                  onClick={() =>
                    generateImage({
                      propertyType,
                      price,
                      downPayment,
                      dpPct,
                      loanAmount,
                      combinedIncome,
                      selectedRate,
                      results: LOAN_TERMS.map((yr) => ({
                        term: yr,
                        monthlyPayment: calcMonthly(
                          loanAmount,
                          selectedRate.rate,
                          yr,
                        ),
                      })),
                      spotlightTerm,
                      spotlightPayment,
                      minRequiredIncome,
                      spotlightRatio,
                      spotlightWithin,
                      maxLoanable,
                    })
                  }
                >
                  ⬇ Download as Image
                </button>
              </div>
            </>
          )}

          {/* Important Notice */}
          <div className="hlc-notice" style={{ paddingTop: 12 }}>
            <p
              style={{
                fontStyle: "italic",
                fontSize: 11,
                fontWeight: 700,
                color: "#444",
                marginBottom: 4,
                marginTop: 0,
              }}
            >
              IMPORTANT NOTICE:
            </p>
            <ol
              style={{
                fontSize: 11,
                color: "#777",
                lineHeight: 1.7,
                paddingLeft: 16,
                margin: 0,
              }}
            >
              <li>All amounts quoted are in Philippine Peso.</li>
              <li>All computations are for illustration purposes only.</li>
            </ol>
          </div>
        </div>
      </div>
    </>
  );
}
